services:
  backend:
    build: ./backend
    ports:
      - "9001:9001"
    env_file:
      - .env
    environment:
      - CORS_ORIGINS=http://localhost:9002

  frontend:
    build:
      context: ./frontend
      args:
        INTERNAL_API_URL: http://backend:9001
    ports:
      - "9002:9002"
    environment:
      - INTERNAL_API_URL=http://backend:9001
      - PORT=9002
    env_file:
      - frontend/.env.local
    depends_on:
      - backend
